# Practices

Estos son ejercicios para practicar acerca de:
- Numpy
- Pandas
- Matplotlib
- Regresion Lineal
- Regresion Logistica

## Numpy

1. Crea un array NumPy de números enteros del 0 al 20 y obtén los elementos que sean múltiplos de 3.

In [5]:
import numpy as np
arr = np.arange(21)
multiples_of_3 = arr[arr % 3 == 0]
print(multiples_of_3)

[ 0  3  6  9 12 15 18]


2. Genera una matriz aleatoria de 5x5 con valores entre 0 y 1.

In [7]:
random_matrix = np.random.rand(5, 5)
print(random_matrix)

[[0.94456229 0.11514925 0.96917291 0.87714922 0.69857918]
 [0.81866412 0.49341277 0.48995913 0.91260412 0.25275362]
 [0.57849735 0.76243236 0.30400709 0.30759399 0.50772815]
 [0.95983429 0.97903252 0.2878621  0.42122685 0.21920196]
 [0.13412098 0.34487903 0.38675954 0.56023568 0.0830939 ]]


3. Crea un array NumPy de 10 elementos y cambia el signo de los números impares.

In [9]:
a = np.arange(10)
a[a % 2 == 1] = -a[a % 2 == 1]
print(a)

[ 0 -1  2 -3  4 -5  6 -7  8 -9]


4. Dado un array 1D, invierte su orden usando slicing.

In [11]:
a = np.arange(10)
a= a[::-1]
print(a)

[9 8 7 6 5 4 3 2 1 0]


5. Multiplica dos matrices de 3x3 usando NumPy.

In [13]:
matriz1 = np.full((3, 3), 2)
matriz2 = np.full((3,3), 4)
print(matriz1 * matriz2)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


6. Crea una matriz identidad de 6x6.

In [15]:
matriz_identidad = np.eye(6)
print(matriz_identidad)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


7. Crea un array con 100 números aleatorios y calcula la media, la mediana y la desviación estándar.

In [17]:
a = np.random.rand(100)
print("Media: ", a.mean())
print("Mediana: ", np.median(a))
print("Desviacion estandar: ", a.std())

Media:  0.46467742454587563
Mediana:  0.40966052749460574
Desviacion estandar:  0.28704101751976396


8. Convierte un array NumPy de 1D a 2D (matriz de 3x3) utilizando `reshape()`.

In [19]:
a = np.arange(9)
matriz = a.reshape(3,3)
matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
matriz = np.random.rand(4, 4)
matriz_inv = np.linalg.inv(matriz)
matriz_inv

array([[ -8.20461604,   6.12369116,  -1.05434612,   2.80456063],
       [ 58.6150375 , -39.01437434,   0.37788686, -15.38575158],
       [  5.92798225,  -4.95773251,   1.05267431,  -0.66822716],
       [-66.56988508,  45.81466679,   0.10522812,  15.88945224]])

10. Implementa la función de costo para una regresión lineal con NumPy.

In [22]:
def costo_funcion(X, y, teta):
    m = len(y)
    predicciones = X.dot(teta)
    costo = (1/(2*m)) * np.sum(np.square(predicciones - y))
    return costo

X = np.array([[1, 3], [1, 2], [1, 3]])
y = np.array([1, 2, 3])
teta = np.array([0, 1])
costo = costo_funcion(X, y, teta)
print(costo)
X, y, teta

0.6666666666666666


(array([[1, 3],
        [1, 2],
        [1, 3]]),
 array([1, 2, 3]),
 array([0, 1]))

## Pandas

1. Crea un DataFrame con los nombres de 5 estudiantes y sus calificaciones en 3 materias. Calcula el promedio de cada estudiante.

In [25]:
import pandas as pd

In [26]:
estudiantes = {
    "Raul": pd.Series([9.0, 8.7, 7.0], ["Programacion", "Quimica", "Estadistica"]),
    "Jose": pd.Series([7.0, 9.7, 8.0], ["Programacion", "Quimica", "Estadistica"]),
    "Maria": pd.Series([9.4, 6.7, 7.0], ["Programacion", "Quimica", "Estadistica"]),
    "Mario": pd.Series([9.0, 9.7, 10.0], ["Programacion", "Quimica", "Estadistica"]),
    "Ramon": pd.Series([8.0, 8.5, 8.0], ["Programacion", "Quimica", "Estadistica"])
}
df = pd.DataFrame(estudiantes)
df["Promedio"] = df[["Raul", "Jose", "Maria", "Mario", "Ramon"]].mean(axis=1)
df

Raul  Jose  Maria  Mario  Ramon  Promedio
Programacion   9.0   7.0    9.4    9.0    8.0      8.48
Quimica        8.7   9.7    6.7    9.7    8.5      8.66
Estadistica    7.0   8.0    7.0   10.0    8.0      8.00

2. Lee un archivo CSV y muestra las 10 primeras filas.

In [28]:
csv = pd.read_csv("../02-Pandas/df_personas.csv")
csv.head(10)

Unnamed: 0  Peso  Altura  Mascotas
0       Anel    60     145       2.0
1     Chucho    74     170       NaN
2     Emilio    72     169       NaN
3    Jocelin    73     170       9.0

3. Dado un DataFrame con información de ventas (producto, cantidad, precio), agrega una columna con el valor total (cantidad x precio).

In [30]:
data = {'Producto': ['A', 'B', 'C'],
        'Cantidad': [10, 5, 8],
        'Precio': [2.5, 3.0, 1.2]}
df = pd.DataFrame(data)
df["Total"] = df["Cantidad"] * df["Precio"]
df

Producto  Cantidad  Precio  Total
0        A        10     2.5   25.0
1        B         5     3.0   15.0
2        C         8     1.2    9.6

4. Filtra un DataFrame para mostrar solo las filas en las que el valor de una columna específica sea mayor que 50.

In [32]:
df = pd.DataFrame([50, 70, 80, 85, 100, 45, 30, 120, 200, 300], columns=["Valores"])
df[df["Valores"] > 50]

Valores
1       70
2       80
3       85
4      100
7      120
8      200
9      300

5. Agrupa un DataFrame de datos de ventas por categorías y calcula la suma de ventas por cada categoría.

In [34]:
data = {'Categoria': ['A', 'A', 'B', 'B', 'C'],
        'Ventas': [100, 200, 150, 130, 300]}
df = pd.DataFrame(data)
venta_categoria= df.groupby("Categoria").sum()
print(venta_categoria)

           Ventas
Categoria        
A             300
B             280
C             300


6. Crea un DataFrame con fechas de un mes y una columna con valores de temperatura diaria. Usa la función rolling() para calcular la media móvil de 7 días.

In [36]:
dates = pd.date_range('2024-01-01', periods=30)
temps = np.random.randint(0, 30, size=30)
df = pd.DataFrame({
    "fechas": dates,
    "temperaturas": temps
})
df['Media_Movil'] = df['temperaturas'].rolling(window=7).mean()
df

fechas  temperaturas  Media_Movil
0  2024-01-01            11          NaN
1  2024-01-02             9          NaN
2  2024-01-03            20          NaN
3  2024-01-04             0          NaN
4  2024-01-05             0          NaN
5  2024-01-06            22          NaN
6  2024-01-07            14    10.857143
7  2024-01-08             6    10.142857
8  2024-01-09             9    10.142857
9  2024-01-10            18     9.857143
10 2024-01-11            16    12.142857
11 2024-01-12            17    14.571429
12 2024-01-13            12    13.142857
13 2024-01-14            21    14.142857
14 2024-01-15            17    15.714286
15 2024-01-16            26    18.142857
16 2024-01-17            19    18.285714
17 2024-01-18            12    17.714286
18 2024-01-19             5    16.000000
19 2024-01-20             6    15.142857
20 2024-01-21             7    13.142857
21 2024-01-22             1    10.857143
22 2024-01-23             3     7.571429
23 2024-01-24            11     6.428571
24 2024-01-25            17     7.142857
25 2024-01-26            11     8.000000
26 2024-01-27            13     9.000000
27 2024-01-28            19    10.714286
28 2024-01-29            10    12.000000
29 2024-01-30            17    14.000000

7. Carga un dataset con información de pacientes, y filtra a los pacientes que tengan más de 40 años y cuyo IMC esté por encima de 25.

In [41]:
#df = pd.read_csv('patients_data.csv')
#filtered_df = df[(df['Edad'] > 40) & (df['IMC'] > 25)]
#print(filtered_df)

8. Realiza una regresión lineal con un DataFrame de pandas para predecir el valor de una variable continua a partir de otra.

In [43]:
from sklearn.linear_model import LinearRegression
import numpy as np
df = pd.DataFrame({'X': [1, 2, 3, 4, 5], 'Y': [2, 4, 5, 4, 5]})
df
X_df = df[["X"]]
y_df = df[["Y"]]
model = LinearRegression().fit(X_df, y_df)
print(f'Coeficiente: {model.coef_}, Intercepto: {model.intercept_}')
X_test = np.array([[10]])
y_pred = model.predict(X_test)
print(y_pred) 

Coeficiente: [[0.6]], Intercepto: [2.2]
[[8.2]]


/opt/anaconda3/envs/Simulacion/lib/python3.9/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
