# Practices

Estos son ejercicios para practicar acerca de:
- Numpy
- Pandas
- Matplotlib
- Regresion Lineal
- Regresion Logistica

## Numpy
1. Crea un array NumPy de números enteros del 0 al 20 y obtén los elementos que sean múltiplos de 3.

In [4]:
import numpy as np
arr = np.arange(21)
multiples_of_3 = arr[arr % 3 == 0]
print(multiples_of_3)

[ 0  3  6  9 12 15 18]


2. Genera una matriz aleatoria de 5x5 con valores entre 0 y 1.

In [6]:
random_matrix = np.random.rand(5, 5)
print(random_matrix)

[[0.99677606 0.94967411 0.29498698 0.53560025 0.29880091]
 [0.68282684 0.91972116 0.85973252 0.84469664 0.09824357]
 [0.09441503 0.94748938 0.10264532 0.41511769 0.51359449]
 [0.6904277  0.8165424  0.45035354 0.25604119 0.61878893]
 [0.58247043 0.91793917 0.17719194 0.06612357 0.65104303]]


3. Crea un array NumPy de 10 elementos y cambia el signo de los números impares.

In [8]:
a = np.arange(10)
a[a % 2 == 1] = -a[a % 2 == 1]
print(a)

[ 0 -1  2 -3  4 -5  6 -7  8 -9]


4. Dado un array 1D, invierte su orden usando slicing.

In [10]:
a = np.arange(10)
a= a[::-1]
print(a)

[9 8 7 6 5 4 3 2 1 0]


5. Multiplica dos matrices de 3x3 usando NumPy.

In [12]:
matriz1 = np.full((3, 3), 2)
matriz2 = np.full((3,3), 4)
print(matriz1 * matriz2)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


6. Crea una matriz identidad de 6x6.

In [14]:
matriz_identidad = np.eye(6)
print(matriz_identidad)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


7. Crea un array con 100 números aleatorios y calcula la media, la mediana y la desviación estándar.

In [16]:
a = np.random.rand(100)
print("Media: ", a.mean())
print("Mediana: ", np.median(a))
print("Desviacion estandar: ", a.std())

Media:  0.5008129573155348
Mediana:  0.49146235716418923
Desviacion estandar:  0.30886337198749797


8. Convierte un array NumPy de 1D a 2D (matriz de 3x3) utilizando `reshape()`.

In [18]:
a = np.arange(9)
matriz = a.reshape(3,3)
matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
matriz = np.random.rand(4, 4)
matriz_inv = np.linalg.inv(matriz)
matriz_inv

array([[-4.03922099,  9.96323645, -7.61003355,  2.4808965 ],
       [ 2.60248847, -6.17682364,  4.13648049, -0.22392859],
       [ 1.4787242 , -0.37810825, -0.34189609, -1.18709803],
       [ 0.62869372, -2.90027916,  3.93189438, -0.91410948]])

10. Implementa la función de costo para una regresión lineal con NumPy.

In [21]:
def costo_funcion(X, y, teta):
    m = len(y)
    predicciones = X.dot(teta)
    costo = (1/(2*m)) * np.sum(np.square(predicciones - y))
    return costo

X = np.array([[1, 3], [1, 2], [1, 3]])
y = np.array([1, 2, 3])
teta = np.array([0, 1])
costo = costo_funcion(X, y, teta)
print(costo)
X, y, teta

0.6666666666666666


(array([[1, 3],
        [1, 2],
        [1, 3]]),
 array([1, 2, 3]),
 array([0, 1]))