# Introduccion a Numpy

**Numpy es una bliblioteca fundamental para la cumputación cientifica con Python.**
* Proporciona arrays N-dimensiones.
* Proporciona funciones matematticas sofesticadas.
* Implementa herramientas para integrar C/C++.
* Proporciona mecanismos para facilitar la realizacion de tareas relacionadas con algebra lineal o números aleatorios.

## Imports

In [4]:
import numpy as np

## Arrays


Un **array** es una estructura de datos que consiste en una coleccion de elementos (valores o variables), cada uno identifcado por almenos un indece o clave. Un **array** se almacena de modo que la posicion de cada elemento se pueda calcular a partir de su tupla de indice mediante uan fórmula matemática. El tipo mas simple de array es un lineal, tambien llamado array unidimensional.  

#### En Numpy:
* Cada dimension de denominda **axis**.
* El numero de dimensiones de denomina **rank**.
* La lista de dimensiones con su correspondiente longitud se denomina **shape**.
* El numero total de elementos (multiplicacion de la longitud de las dimensiones) se denomina **size**.

In [8]:
# Array cuyos valores son todos 0
a = np.zeros((2,4))

In [9]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**a** es un array:
* Con dos **axis**, elprimero de longitud 2 y el segundo de longitud 4.
* Con un **rank** igual a 2.
* Con un **shape** igual a (2,4).
* Con un **size** igual a 8.

In [11]:
a.shape

(2, 4)

In [12]:
a.ndim

2

In [13]:
a.size

8

### Creación de Arrays

In [15]:
# Array cuyos valores son todos 0.
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
# Array cuyos valores son todos 1
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [17]:
# Array cuyos valores son todos indicados
np.full((2, 3, 4), 8)

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [ ]:
# Aqui me faltan 2 ejemplos 

In [18]:
# Creacion de una funcion basada en rangos
# (min, max, numero de elementos del array)
print(np.linspace(0, 6, 10))

[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]


In [29]:
# Inicializar un array con valores alatorios
np.random.rand(2, 3, 4)

array([[[0.5927113 , 0.32085669, 0.23408556, 0.88248261],
        [0.49478963, 0.44888918, 0.55702587, 0.71981015],
        [0.37951464, 0.49502189, 0.39927643, 0.26423274]],

       [[0.50896284, 0.18569562, 0.79631242, 0.1302455 ],
        [0.3335445 , 0.73206417, 0.64393201, 0.00750344],
        [0.22408472, 0.46302489, 0.04444763, 0.48121229]]])

In [31]:
# Inicializar un array con valores aleatorios conforme a una distrubucion normal
np.random.randn(2, 4)

array([[ 1.31639697, -0.80292635, -0.81633259,  0.03546202],
       [-1.25571647,  0.1906906 , -0.49384093, -0.39911751]])